baseurl = "http://example.org"
title = "Dimension"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true
googleAnalytics = "UA-123-45"

[params]
  title = "Omar Khaled"
  description = '<!--[-->Cross Platform Developer (React / React Native)<!--]--><br />'
  logo = ""
  copyright = ""

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/omar.khaled.587606"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/omarkhaled11"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Omar Khaled"
description = '<!--[-->Cross Platform Developer (React / React Native)<!--]--><br />'

[languages.de]
languageName = ""
weight = 2
title = "Dimension"
description = '<!--[-->Cross Platform Developer<!--]--><br />'

